module.exports = [
  {
    id: 1,
    icon: 'laptop',
    name: '用户中心',
    router: '/user/dashboard',
  },
  {
    id: 2,
    bpid: 1,
    name: 'User Manage',
    icon: 'user',
    router: '/user/manager',
  },
   
  {
    id: 21,
    mpid: -1,
    bpid: 2,
    name: 'User Detail',
    router: '/user/:id',
  },
  {
    id: 3,
    bpid: 1,
    name: '修改密码',
    icon: 'user',
    router: '/user/password',
  },
  {
    id: 4,
    bpid: 1,
    name: 'Request',
    icon: 'api',
    router: '/user/request',
  },
  {
    id: 5,
    bpid: 1,
    name: 'UI Element',
    icon: '/user/camera-o',
  },
  {
    id: 51,
    bpid: 5,
    mpid: 5,
    name: 'IconFont',
    icon: 'heart-o',
    router: '/user/UIElement/iconfont',
  },
  {
    id: 52,
    bpid: 5,
    mpid: 5,
    name: 'DataTable',
    icon: 'database',
    router: '/user/UIElement/dataTable',
  },
  {
    id: 53,
    bpid: 5,
    mpid: 5,
    name: 'DropOption',
    icon: 'bars',
    router: '/user/UIElement/dropOption',
  },
  {
    id: 54,
    bpid: 5,
    mpid: 5,
    name: 'Search',
    icon: 'search',
    router: '/user/UIElement/search',
  },
  {
    id: 55,
    bpid: 5,
    mpid: 5,
    name: 'Editor',
    icon: 'edit',
    router: '/user/UIElement/editor',
  },
  {
    id: 56,
    bpid: 5,
    mpid: 5,
    name: 'layer (Function)',
    icon: 'credit-card',
    router: '/user/UIElement/layer',
  },
  {
    id: 6,
    bpid: 1,
    name: 'Recharts',
    icon: 'code-o',
  },
  {
    id: 61,
    bpid: 6,
    mpid: 6,
    name: 'LineChart',
    icon: 'line-chart',
    router: '/user/chart/lineChart',
  },
  {
    id: 62,
    bpid: 6,
    mpid: 6,
    name: 'BarChart',
    icon: 'bar-chart',
    router: '/user/chart/barChart',
  },
  {
    id: 63,
    bpid: 6,
    mpid: 6,
    name: 'AreaChart',
    icon: 'area-chart',
    router: '/user/chart/areaChart',
  },
  {
    id: 7,
    bpid: 1,
    name: 'Test Navigation',
    icon: 'setting',
  },
  {
    id: 71,
    bpid: 7,
    mpid: 7,
    name: 'Test Navigation1',
    router: '/user/navigation/navigation1',
  },
  {
    id: 72,
    bpid: 7,
    mpid: 7,
    name: 'Test Navigation2',
    router: '/user/navigation/navigation2',
  },
  {
    id: 721,
    bpid: 72,
    mpid: 72,
    name: 'Test Navigation21',
    router: '/user/navigation/navigation2/navigation1',
  },
  {
    id: 722,
    bpid: 72,
    mpid: 72,
    name: 'Test Navigation22',
    router: '/user/navigation/navigation2/navigation2',
  },
]
